# Generated by Django 4.0 on 2021-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('verygood', 'Very Good'), ('good', 'Good'), ('mediocre', 'Mediocre'), ('bad', 'Bad'), ('verybad', 'Very Bad')], max_length=10)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
